import { prisma } from './prisma';

export async function logAction(
  actorUserId: string | null,
  action: string,
  entityType?: string,
  entityId?: string,
  payload?: unknown
) {
  try {
    const activity = await prisma.activityLog.create({
      data: {
        actorUserId,
        action,
        entityType,
        entityId,
        payload: payload ? JSON.parse(JSON.stringify(payload)) : null,
      },
    });

    console.log(`Activity logged: ${action} by ${actorUserId || 'system'}`);
    return activity;
  } catch (error) {
    console.error('Failed to log activity:', error);
    // Don't throw - logging should not break the main operation
    return null;
  }
}

// Convenience functions for common actions
export const ActivityActions = {
  ASSET_CREATED: 'ASSET_CREATED',
  ASSET_UPDATED: 'ASSET_UPDATED',
  ASSET_DELETED: 'ASSET_DELETED',
  ASSET_ASSIGNED: 'ASSET_ASSIGNED',
  ASSET_LINKED_PROJECT: 'ASSET_LINKED_PROJECT',
  
  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED: 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_DELETED: 'SUBSCRIPTION_DELETED',

  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',

  ALERT_SUBSCRIPTION_RENEWAL: 'ALERT_SUBSCRIPTION_RENEWAL',
  ALERT_WARRANTY_EXPIRY: 'ALERT_WARRANTY_EXPIRY',
  
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',

  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
  SUPPLIER_DELETED: 'SUPPLIER_DELETED',
  SUPPLIER_APPROVED: 'SUPPLIER_APPROVED',
  SUPPLIER_REJECTED: 'SUPPLIER_REJECTED',

  // Task Management actions
  BOARD_CREATED: 'BOARD_CREATED',
  BOARD_UPDATED: 'BOARD_UPDATED',
  BOARD_DELETED: 'BOARD_DELETED',
  BOARD_ARCHIVED: 'BOARD_ARCHIVED',
  BOARD_RESTORED: 'BOARD_RESTORED',
  BOARD_MEMBER_ADDED: 'BOARD_MEMBER_ADDED',
  BOARD_MEMBER_REMOVED: 'BOARD_MEMBER_REMOVED',
  BOARD_MEMBER_UPDATED: 'BOARD_MEMBER_UPDATED',

  COLUMN_CREATED: 'COLUMN_CREATED',
  COLUMN_UPDATED: 'COLUMN_UPDATED',
  COLUMN_DELETED: 'COLUMN_DELETED',
  COLUMN_REORDERED: 'COLUMN_REORDERED',

  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_DELETED: 'TASK_DELETED',
  TASK_MOVED: 'TASK_MOVED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_REOPENED: 'TASK_REOPENED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_UNASSIGNED: 'TASK_UNASSIGNED',

  TASK_LABEL_CREATED: 'TASK_LABEL_CREATED',
  TASK_LABEL_UPDATED: 'TASK_LABEL_UPDATED',
  TASK_LABEL_DELETED: 'TASK_LABEL_DELETED',

  TASK_COMMENT_ADDED: 'TASK_COMMENT_ADDED',
  TASK_COMMENT_UPDATED: 'TASK_COMMENT_UPDATED',
  TASK_COMMENT_DELETED: 'TASK_COMMENT_DELETED',

  TASK_ATTACHMENT_ADDED: 'TASK_ATTACHMENT_ADDED',
  TASK_ATTACHMENT_DELETED: 'TASK_ATTACHMENT_DELETED',

  TASK_CHECKLIST_ITEM_ADDED: 'TASK_CHECKLIST_ITEM_ADDED',
  TASK_CHECKLIST_ITEM_COMPLETED: 'TASK_CHECKLIST_ITEM_COMPLETED',
  TASK_CHECKLIST_ITEM_DELETED: 'TASK_CHECKLIST_ITEM_DELETED',

  // Purchase Request actions
  PURCHASE_REQUEST_CREATED: 'PURCHASE_REQUEST_CREATED',
  PURCHASE_REQUEST_UPDATED: 'PURCHASE_REQUEST_UPDATED',
  PURCHASE_REQUEST_DELETED: 'PURCHASE_REQUEST_DELETED',
  PURCHASE_REQUEST_STATUS_CHANGED: 'PURCHASE_REQUEST_STATUS_CHANGED',
  PURCHASE_REQUEST_APPROVED: 'PURCHASE_REQUEST_APPROVED',
  PURCHASE_REQUEST_REJECTED: 'PURCHASE_REQUEST_REJECTED',
  PURCHASE_REQUEST_COMPLETED: 'PURCHASE_REQUEST_COMPLETED',
} as const;

export type ActivityAction = typeof ActivityActions[keyof typeof ActivityActions];